name: Deploy Firebase Functions

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install dependencies
      - name: Install production dependencies
        working-directory: ./functions
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Install development dependencies
      - name: Install development dependencies
        working-directory: ./functions
        run: pip install -r requirements-dev.txt

      # 5. Create .env file from GitHub Secrets
      - name: Create .env file
        working-directory: ./functions
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      # 6. Run tests
      - name: Run tests
        working-directory: ./functions
        run: pytest tests/ -v

      # 7. Run tests with coverage
      - name: Run tests with coverage
        working-directory: ./functions
        run: pytest tests/ --cov=src --cov-report=xml --cov-report=term

      # 8. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 9. Deploy to Firebase Functions
      - name: Deploy to Firebase Functions
        run: firebase deploy --only functions --project "${{ secrets.FIREBASE_PROJECT_ID }}" --token "${{ secrets.FIREBASE_TOKEN }}"
        working-directory: ./functions

      # 10. Verify deployment
      - name: Verify deployment
        run: |
          echo "✅ Firebase Functions deployed successfully!"
          echo "Functions available at:"
          echo "- calculate_horoscope"
          echo "- calculate_aspects" 
          echo "- moon_phase"
