name: Test Firebase Functions

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Create virtual environment
      - name: Create virtual environment
        working-directory: ./functions
        run: python -m venv venv

      # 4. Install dependencies
      - name: Install production dependencies
        working-directory: ./functions
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Install development dependencies
      - name: Install development dependencies
        working-directory: ./functions
        run: |
          source venv/bin/activate
          pip install -r requirements-dev.txt

      # 6. Create .env file from GitHub Secrets
      - name: Create .env file
        working-directory: ./functions
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      # 7. Run tests
      - name: Run tests
        working-directory: ./functions
        run: |
          source venv/bin/activate
          pytest tests/ -v

      # 8. Run tests with coverage
      - name: Run tests with coverage
        working-directory: ./functions
        run: |
          source venv/bin/activate
          pytest tests/ --cov=src --cov-report=xml --cov-report=term

      # 8. Upload coverage to Codecov (optional)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./functions/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
